<?php

/**
 * @file
 * The Social course module.
 */

use Drupal\block\Entity\Block;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Block\BlockPluginInterface;
use Drupal\Core\Link;
use Drupal\Core\Url;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Cache\Cache;
use Drupal\group\Entity\GroupContent;
use Drupal\social_course\Controller\CoursesController;
use Drupal\group\Entity\GroupInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\views\ViewExecutable;
use Drupal\node\Entity\Node;
use Drupal\social_course\CourseEnrollmentInterface;
use Drupal\node\NodeInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Database\Query\AlterableInterface;
use Drupal\Core\Database\Query\SelectInterface;
use Drupal\Core\Entity\EntityFormInterface;

const SOCIAL_COURSE_STATUS_ENROLLED = 'enrolled';
const SOCIAL_COURSE_STATUS_STARTED = 'started';
const SOCIAL_COURSE_STATUS_FINISHED = 'finished';

const SOCIAL_COURSE_SEQUENTIAL = 1;
const SOCIAL_COURSE_NOT_SEQUENTIAL = 2;

/**
 * Implements hook_theme().
 */
function social_course_theme($existing, $type, $theme, $path) {
  return [
    'course_add_list' => [
      'variables' => [
        'content' => NULL,
      ],
    ],
    'group__course__hero' => [
      'render element' => 'elements',
      'base hook' => 'group',
    ],
    'course_material_hero' => [
      'variables' => [
        'title' => NULL,
        'hero_node' => NULL,
        'node' => NULL,
        'node_type' => NULL,
        'section_class' => NULL,
        'parent_course' => NULL,
        'parent_section' => NULL,
        'material' => NULL,
      ],
    ],
    'course_material_pager' => [
      'variables' => [
        'material' => NULL,
      ],
    ],
    'course_material_navigation' => [
      'variables' => [
        'items' => [],
        'parent_course' => NULL,
        'parent_section' => NULL,
      ],
    ],
    'node__section__teaser' => [
      'base hook' => 'node',
    ],
    'node__article__full' => [
      'base hook' => 'node',
    ],
    'node__video__full' => [
      'base hook' => 'node',
    ],
  ];
}

/**
 * Prepares variables for the social page hero data.
 *
 * Default template: page-hero-data.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - title: Page title as a string
 *   - node_type: Type of node
 *   - section_class: Class based on type of node
 *   - parent_section: Information about parent section
 *   - material: Information about materials parent section
 *   - parent_course: Information about parent course
 */
function template_preprocess_course_material_hero(&$variables) {
  $type = [
    'article',
    'video',
  ];

  \Drupal::moduleHandler()->alter('social_course_material_types', $type);

  // Get current user.
  $account = \Drupal::currentUser();

  // Get current node object or node id.
  $node = \Drupal::routeMatch()->getParameter('node');

  if (!is_object($node) && !is_null($node)) {
    $node = \Drupal::service('entity_type.manager')
      ->getStorage('node')
      ->load($node);
  }

  if ($node instanceof NodeInterface && in_array($node->getType(), $type)) {
    // Get the current route name to check if the user is on the edit or delete page.
    $route = \Drupal::routeMatch()->getRouteName();

    if (!in_array($route, array('entity.node.edit_form','entity.node.delete_form'))) {
      if ($node->access('update', $account)) {
        $variables['node_edit_url'] = $node->toUrl('edit-form')->toString();
      }
    }

    /** @var \Drupal\social_course\CourseWrapperInterface $course_wrapper */
    $course_wrapper = \Drupal::service('social_course.course_wrapper');
    $course_wrapper->setCourseFromMaterial($node);
    $section = $course_wrapper->getSectionFromMaterial($node);

    $variables['node_type'] = $node->getType();
    $variables['parent_course'] = [
      'label' => $course_wrapper->getCourse()->label(),
      'url' => $course_wrapper->getCourse()->toUrl(),
    ];

    $variables['parent_section'] = [
      'number' => $course_wrapper->getSectionNumber($section) + 1,
      'title' => $section->label(),
      'url' => $section->toUrl(),
    ];

    $variables['material'] = [
      'number' => $course_wrapper->getMaterialNumber($node) + 1,
      'count' => count($course_wrapper->getMaterials($section)),
    ];
  }
}

/**
 * Prepares variables for the material page navigation data.
 *
 * @param array $variables
 *   An associative array containing:
 *   - material: Information about materials in parent section
 */
function template_preprocess_course_material_pager(&$variables) {
  $type = [
    'article',
    'video',
  ];

  \Drupal::moduleHandler()->alter('social_course_material_types', $type);

  // Get current node object or node id.
  $node = \Drupal::routeMatch()->getParameter('node');

  if (is_numeric($node)) {
    $node = \Drupal::entityTypeManager()
      ->getStorage('node')
      ->load($node);
  }

  if ($node instanceof NodeInterface && in_array($node->getType(), $type)) {
    /** @var \Drupal\social_course\CourseWrapperInterface $course_wrapper */
    $course_wrapper = \Drupal::service('social_course.course_wrapper');
    $course_wrapper->setCourseFromMaterial($node);

    $section = $course_wrapper->getSectionFromMaterial($node);
    $materials = $course_wrapper->getMaterials($section);
    $material_number = $course_wrapper->getMaterialNumber($node) + 1;
    $variables['material']['number'] = $material_number;
    $variables['material']['count'] = count($materials);

    // Create link to previous material.
    if ($material_number > 1) {
      $previous_url = Url::fromRoute('entity.node.canonical', [
        'node' => $course_wrapper->getMaterial($node, -1)->id(),
      ], [
        'attributes' => [
          'class' => [
            'btn',
            'btn-raised',
            'btn-default',
            'waves-effect',
          ],
        ],
      ]);

      $variables['material']['previous'] = Link::fromTextAndUrl(t('Previous'), $previous_url)
        ->toRenderable();
    }

    // Create link to next material.
    if ($material_number < count($materials)) {
      $account = \Drupal::currentUser();
      $storage = \Drupal::entityTypeManager()->getStorage('course_enrollment');
      $course_enrollment = $storage->loadByProperties([
        'gid' => $course_wrapper->getCourse()->id(),
        'sid' => $section->id(),
        'mid' => $node->id(),
        'uid' => $account->id(),
      ]);
      $course_enrollment = current($course_enrollment);

      if (($course_enrollment && $course_enrollment->getStatus() === CourseEnrollmentInterface::FINISHED) || !$course_wrapper->sectionAccess($section, $account, 'continue')) {
        $next_url = Url::fromRoute('entity.node.canonical', [
          'node' => $course_wrapper->getMaterial($node, 1)->id(),
        ], [
          'attributes' => [
            'class' => [
              'btn',
              'btn-raised',
              'waves-effect',
              'next-material',
            ],
          ],
        ]);
      }
      else {
        $next_url = Url::fromRoute('social_course.next_material', [
          'group' => $course_wrapper->getCourse()->id(),
          'node' => $section->id(),
        ], [
          'attributes' => [
            'class' => [
              'btn',
              'btn-raised',
              'waves-effect',
              'next-material',
            ],
          ],
        ]);
      }

      $variables['material']['next'] = Link::fromTextAndUrl(t('Continue'), $next_url)
        ->toRenderable();
    }
    else {
      $next_url = Url::fromRoute('social_course.next_material', [
        'group' => $course_wrapper->getCourse()->id(),
        'node' => $section->id(),
      ], [
        'attributes' => [
          'class' => [
            'btn',
            'btn-raised',
            'btn-primary',
            'waves-effect',
          ],
        ],
      ]);

      $section_number = $course_wrapper->getSectionNumber($section) + 1;
      $title = $section_number < count($course_wrapper->getSections()) ? t('Finish section') : t('Finish course');
      $variables['material']['next'] = Link::fromTextAndUrl($title, $next_url)
        ->toRenderable();
    }
  }
}

/**
 * Implements hook_block_view_BASE_BLOCK_ID_alter() for account_header_block.
 * @param array $build
 * @param \Drupal\Core\Block\BlockPluginInterface $block
 */
function social_course_block_view_account_header_block_alter(array &$build, BlockPluginInterface $block) {
  $build['#pre_render'][] = 'social_course_block_view_account_header_block_pre_render';
}

/**
 * Pre-render callback for block account_header_block.
 * @param array $build
 * @return array
 */
function social_course_block_view_account_header_block_pre_render(array $build) {
  $account = \Drupal::currentUser();

  // Add Courses link.
  $build['content']['#links']['add']['below']['add_course'] = [
    'classes' => '',
    'link_attributes' => '',
    'link_classes' => '',
    'icon_classes' => '',
    'icon_label' => '',
    'title' => t('Create New Course'),
    'label' => t('New course'),
    'title_classes' => '',
    'url' => Url::fromRoute('social_course.course_add'),
    'access' => CoursesController::access($account)->isAllowed(),
  ];

  // My Courses link.
  if (isset($build['content']['#links']['account_box']['below'])) {
    $url = Url::fromRoute('view.courses_user.page', [
      'user' => $account->id(),
    ]);
    $my_courses = [
      'classes' => '',
      'link_attributes' => '',
      'link_classes' => '',
      'icon_classes' => '',
      'icon_label' => '',
      'title' => t('View my courses'),
      'label' => t('My courses'),
      'title_classes' => '',
      'url' => $url,
      'access' => $url->access(),
    ];

    $links = $build['content']['#links']['account_box']['below'];

    // Find our reference key.
    $divider_idx = array_search('divide_content', array_keys($links));

    // If we can't find it, we just guess at the position.
    if ($divider_idx === FALSE) {
      $divider_idx = 6;
    }

    $links = array_slice($links, 0, $divider_idx, TRUE) +
      ['my_courses' => $my_courses] +
      array_slice($links, $divider_idx, NULL, TRUE);

    $build['content']['#links']['account_box']['below'] = $links;
  }

  return $build;
}

/**
 * Prepares variables for list of available node type templates.
 *
 * Default template: node-add-list.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - content: An array of content types.
 *
 * @see node_add_page()
 */
function template_preprocess_course_add_list(&$variables) {
  $variables['types'] = [];

  if (!empty($variables['content'])) {
    foreach ($variables['content'] as $type) {
      $group_type = $type->id();

      $variables['types'][$group_type] = [
        'type' => $group_type,
        'add_link' => Link::fromTextAndUrl($type->label(), Url::fromRoute('entity.group.add_form', [
          'group_type' => $type->id(),
        ]))->toString(),
        'description' => [
          '#markup' => $type->getDescription(),
        ],
      ];
    }
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function social_course_preprocess_menu(&$variables) {
  $items = $variables['items'];
  $accessible_items = [];
  $account = \Drupal::currentUser();

  foreach ($items as $key => &$item) {
    // Enable recursive parsing.
    if (!empty($item['below'])) {
      $below = [
        'items' => $item['below'],
      ];

      social_course_preprocess_menu($below);
      $item['below'] = $below['items'];
    }

    if (!$item['url']->access($account)) {
      continue;
    }
    else {
      $accessible_items[$key] = $item;
    }
  }

  $variables['items'] = $accessible_items;
}

/**
 * Implements hook_form_alter().
 */
function social_course_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Add and edit forms.
  $course_forms = [
    'group_course_basic_add_form',
    'group_course_basic_edit_form',
    'group_course_advanced_add_form',
    'group_course_advanced_edit_form',
  ];

  if (in_array($form_id, $course_forms)) {
    $form['uid']['widget'][0]['target_id']['#title'] = t('Author');
    $form['actions']['submit']['#submit'][] = '_social_course_group_form_submit';

    // Add widget to sort sections.
    $group = $form_state->getFormObject()->getEntity();

    if ($group->id()) {
      $group_content_storage = \Drupal::entityTypeManager()->getStorage('group_content');
      $content = $group_content_storage->loadByGroup($group, 'group_node:section');

      $form['sections'] = [
        '#type' => 'fieldset',
        '#title' => t('Sections'),
        '#access' => !empty($content),
        '#tree' => TRUE,
      ];

      $form['sections']['help'] = [
        '#type' => 'details',
        '#title' => t('Drag and drop to change the order'),
      ];

      $form['sections']['list'] = [
        '#type' => 'table',
        '#tabledrag' => [
          [
            'action' => 'order',
            'relationship' => 'sibling',
            'group' => 'section-item-weight',
          ],
        ],
        '#header' => [
          t('Title'),
          t('Weight'),
        ],
      ];

      foreach ($content as $item) {
        $entity = $item->getEntity();
        $weight = $entity->get('field_section_weight')->value;
        $form['sections']['list'][ $entity->id() ]['#weight'] = $weight;
        $form['sections']['list'][ $entity->id() ]['#attributes']['class'][] = 'draggable';

        $form['sections']['list'][ $entity->id() ]['label'] = [
          '#markup' => '<span>' . $entity->label() . '</span>',
        ];

        $form['sections']['list'][ $entity->id() ]['weight'] = [
          '#type' => 'textfield',
          '#title' => t('Weight for @title', [
            '@title' => $entity->label(),
          ]),
          '#title_display' => 'invisible',
          '#default_value' => $weight,
          '#attributes' => [
            'class' => [
              'section-item-weight',
            ],
          ],
        ];
      }

      uasort($form['sections']['list'], function ($a, $b) {
        if (!isset($a['#weight']) || !isset($b['#weight']) || $a['#weight'] == $b['#weight']) {
          return 0;
        }

        return $a['#weight'] < $b['#weight'] ? -1 : 1;
      });
    }

    $widget = &$form['field_course_redirect_url']['widget'][0];
    $widget['uri']['#description'] = $widget['#description'];
    $widget['uri']['#type'] = 'textfield';
  }

  // Action forms.
  $action_forms = [
    'group_content_course_basic-group_membership_group-join_form',
    'group_content_course_basic-group_membership_group-leave_form',
    'group_content_course_basic-group_membership_add_form',
    'group_content_course_advanced-group_membership_group-join_form',
    'group_content_course_advanced-group_membership_group-leave_form',
    'group_content_course_advanced-group_membership_add_form',
  ];

  // Perform alterations on joining / leaving groups.
  if (in_array($form_id, $action_forms)) {
    // Add cancel option on join and leave form.
    $form['actions']['cancel'] = [
      '#type' => 'submit',
      '#value' => t('Cancel'),
      '#submit' => ['_social_group_cancel_join_leave_form'],
      '#limit_validation_errors' => [],
    ];

    $form['actions']['submit']['#submit'][] = '_social_course_action_form_submit';

    $form['#attributes']['class'][] = 'form--default';

    if(isset($form['actions']['submit'])) {
      $form['actions']['submit']['#button_type'] = 'primary';
      $form['actions']['submit']['#button_level'] = 'raised';
    }

    if (isset($form['actions']['cancel'])) {
      // Some `cancel` buttons are not inputs but links
      if (isset($form['actions']['cancel']['#type']) &&  $form['actions']['cancel']['#type'] == 'link') {
        $form['actions']['cancel']['#attributes']['class'][] = 'btn btn-flat';
      }
      else {
        $form['actions']['cancel']['#button_type'] = 'flat';
      }
    }

    switch ($form_id) {
      case 'group_content_course_basic-group_membership_add_form':
      case 'group_content_course_advanced-group_membership_add_form':
        // Make the form a card and exclude the title.
        $form['#attributes']['class'][] = 'card';
        $form['actions']['#prefix'] = '</div></div>';
        break;

      case 'group_content_course_basic-group_membership_group-join_form':
      case 'group_content_course_advanced-group_membership_group-join_form':
        $form['actions']['submit']['#value'] = t('Enroll in course');

        if (isset($form['path'])) {
          $form['path']['#access'] = FALSE;
        }

        // Make the form a card and exclude the title.
        $form['#attributes']['class'][] = 'card';
        $form['actions']['#prefix'] = '</div></div>';

        $form['help'] = [
          '#type' => 'item',
          '#markup' => t('By enrolling you will be able to follow this course.'),
        ];
        break;

      case 'group_content_course_basic-group_membership_group-leave_form':
      case 'group_content_course_advanced-group_membership_group-leave_form':
        // Extract the actions form the card.
        $form['description']['#prefix'] = '<div class="clearfix">';
        $form['description']['#suffix'] = '</div></div></div>';
        $form['actions']['submit']['#value'] = t('Cancel enrollment');
        break;
    }
  }

  // Delete membership forms.
  $delete_membership_forms = [
    'group_content_course_basic-group_membership_delete_form',
    'group_content_course_advanced-group_membership_delete_form',
  ];

  if (in_array($form_id, $delete_membership_forms)) {
    $form['actions']['submit']['#submit'][] = '_social_membership_delete_form_submit';
  }

  // Memberhsip forms.
  $membership_forms = [
    'group_content_course_basic-group_membership_add_form',
    'group_content_course_basic-group_membership_edit_form',
    'group_content_course_advanced-group_membership_add_form',
    'group_content_course_advanced-group_membership_edit_form',
  ];

  if (in_array($form_id, $membership_forms)) {
    // Change titles on membership forms.
    $form['entity_id']['widget'][0]['target_id']['#title'] = t('Select a member');
    $form['group_roles']['widget']['#title'] = t('Group roles');

    if ('group_content_course_basic-group_membership_edit_form' == $form_id) {
      // Remove the user selection autocomplete on editing group membership.
      $form['entity_id']['#access'] = FALSE;

      // Add redirect to Group Membership page.
      $form['actions']['submit']['#submit'][] = '_social_group_membership_edit_form_submit';
    }
  }

  // Open an Closed group Add and edit forms.
  $group_forms = [
    'group_open_group_add_form',
    'group_open_group_edit_form',
    'group_closed_group_add_form',
    'group_closed_group_edit_form',
  ];

  if (in_array($form_id, $group_forms)) {
    $form['actions']['submit']['#value'] = t('Save');
  }

  // Remove Courses from Social Group add form
  if($form_id == 'social_group_add'){
    $excluded_groups = ['course_advanced', 'course_basic'];
    foreach ($excluded_groups as $excluded_group) {
      if (isset($form['group_settings']['group_type']['#options'][$excluded_group])) {
        unset($form['group_settings']['group_type']['#options'][$excluded_group]);
      }
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function social_course_form_group_public_group_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (empty($form['group_type']['#options'])) {
    return;
  }

  $course_wrapper = \Drupal::service('social_course.course_wrapper');
  $available_bundles = $course_wrapper::getAvailableBundles();

  $form['group_type']['#options'] = array_filter($form['group_type']['#options'], function ($key) use ($available_bundles) {
    return !in_array($key, $available_bundles);
  }, ARRAY_FILTER_USE_KEY);
}

/**
 * Form submit for group join / leave form.
 */
function _social_course_action_form_submit($form, FormStateInterface $form_state) {
  $group = $form_state->getFormObject()->getEntity()->getGroup();

  // Invalidate cache tags.
  $cache_tags = _social_group_cache_tags($group);
  Cache::invalidateTags($cache_tags);

  // Get form that was submitted.
  $complete_form = $form_state->getCompleteForm();

  $join_forms = [
    'group_content_course_basic-group_membership_group-join_form',
    'group_content_course_advanced-group_membership_group-join_form',
  ];

  if (in_array($complete_form['#form_id'], $join_forms)) {
    // Set redirect to group home page.
    $form_state->setRedirect('entity.group.canonical', [
      'group' => $group->id(),
    ]);
  }
  else {
    // Set redirect to the Group overview page when a user saves their profile.
    $form_state->setRedirect('view.groups.page_user_groups', [
      'user' => \Drupal::currentUser()->id(),
    ]);
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function social_course_preprocess_group(&$variables) {
  $group = $variables['group'];
  /** @var \Drupal\social_course\CourseWrapper $course_wrapper */
  $course_wrapper = \Drupal::service('social_course.course_wrapper');
  $bundles = $course_wrapper::getAvailableBundles();

  if (in_array($group->bundle(), $bundles)) {
    $course_wrapper->setCourse($group);

    // Count number of course sections.
    $sections = $course_wrapper->getSections();
    $variables['course_sections'] = count($sections);

    // Get Course status.
    $variables['course_status'] = FALSE;
    $account = \Drupal::currentUser();

    // Get Course published status.
    if ($course_wrapper->getCoursePublishedStatus() == 0) {
      $variables['status_label'] = t('Unpublished');
    }

    if ($group->getMember($account)) {
      $course_wrapper->setCourse($group);

      switch ($course_wrapper->getCourseStatus($account)) {
        case CourseEnrollmentInterface::NOT_STARTED:
          $variables['course_status'] = SOCIAL_COURSE_STATUS_ENROLLED;
          break;

        case CourseEnrollmentInterface::IN_PROGRESS:
          $variables['course_status'] = SOCIAL_COURSE_STATUS_STARTED;
          break;

        case CourseEnrollmentInterface::FINISHED:
          $variables['course_status'] = SOCIAL_COURSE_STATUS_FINISHED;
          break;
      }
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_insert() for group_content entities.
 */
function social_course_group_content_insert(GroupContent $group_content) {
  /** @var \Drupal\social_course\CourseWrapper $course_wrapper */
  $course_wrapper = \Drupal::service('social_course.course_wrapper');
  $bundles = $course_wrapper::getAvailableBundles();
  $group = $group_content->getGroup();

  if (!in_array($group->bundle(), $bundles)) {
    return;
  }

  $course_wrapper->setCourse($group);
  $sections = $course_wrapper->getSections();

  switch ($group_content->getContentPlugin()->getPluginId()) {
    case 'group_node:section':
      // Invalidate cache tags.
      $cache_tags = _social_group_cache_tags($group);
      Cache::invalidateTags($cache_tags);

      $entity = $group_content->getEntity();

      if ($entity->getEntityTypeId() == 'node' && $entity->bundle() == 'section') {
        if (isset($sections[ $entity->id() ])) {
          unset($sections[ $entity->id() ]);
        }

        if ($section = end($sections)) {
          $weight = $section->get('field_section_weight')->value + 1;
          $entity->get('field_section_weight')->setValue($weight);
          $entity->save();
        }
      }
      break;

    case 'group_membership':
      foreach ($sections as $section) {
        Cache::invalidateTags($section->getCacheTags());
      }

      $cache_tags = _social_group_cache_tags($group);
      Cache::invalidateTags($cache_tags);
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 */
function social_course_group_content_delete(GroupContent $group_content) {
  /** @var \Drupal\social_course\CourseWrapper $course_wrapper */
  $course_wrapper = \Drupal::service('social_course.course_wrapper');
  $bundles = $course_wrapper::getAvailableBundles();
  $group = $group_content->getGroup();

  if (!in_array($group->bundle(), $bundles)) {
    return;
  }

  $course_wrapper->setCourse($group);
  $sections = $course_wrapper->getSections();

  switch ($group_content->getContentPlugin()->getPluginId()) {
    case 'group_membership':
      foreach ($sections as $section) {
        Cache::invalidateTags($section->getCacheTags());
      }

      $cache_tags = _social_group_cache_tags($group);
      Cache::invalidateTags($cache_tags);
      break;
  }
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function social_course_menu_local_tasks_alter(&$data, $route_name) {
  $group = _social_group_get_current_group();

  if ($group instanceof GroupInterface) {
    /** @var \Drupal\social_course\CourseWrapper $course_wrapper */
    $course_wrapper = \Drupal::service('social_course.course_wrapper');
    $bundles = $course_wrapper::getAvailableBundles();

    if (!in_array($group->bundle(), $bundles)) {
      return;
    }

    if ($group->bundle() == 'course_basic') {
      foreach (['social_group.events', 'social_group.topics', 'social_course.group_stream', 'social_group.members'] as $key) {
        if (isset($data['tabs'][0][$key])) {
          $data['tabs'][0][$key]['#access'] = AccessResult::forbidden();
        }
      }
    }

    if (isset($data['tabs'][0]['social_group.about'])) {
      $data['tabs'][0]['social_group.about']['#link']['title'] = t('Sections');
    }

    if (isset($data['tabs'][0]['group.view'])) {
      $data['tabs'][0]['group.view']['#access'] = AccessResult::forbidden();
    }
  }
}

/**
 * Form submit for group form.
 */
function _social_course_group_form_submit($form, FormStateInterface $form_state) {
  /** @var \Drupal\group\Entity\GroupInterface $group */
  $group = $form_state->getFormObject()->getEntity();

  if ($group instanceof Group) {
    $form_state->setRedirect('view.group_information.page_group_about', [
      'group' => $group->id(),
    ]);
  }

  $sections_list = $form_state->getValue(['sections', 'list'], []);

  if (is_array($sections_list)) {
    foreach ($sections_list as $nid => $value) {
      if ($node = Node::load($nid)) {
        $node->get('field_section_weight')->setValue($value['weight']);
        $node->save();
      }
    }
  }
}

/**
 * Implements hook_node_grants().
 */
function social_course_node_grants(AccountInterface $account, $op) {
  if ($op != 'view' || $account->hasPermission('bypass group access')) {
    return [];
  }

  $grants = [];
  $plugin_id = 'group_node:section';
  $entity_type_manager = \Drupal::entityTypeManager();
  $group_types = $entity_type_manager->getStorage('group_type')->loadMultiple([
    'course_advanced',
    'course_basic',
  ]);

  foreach ($group_types as $group_type) {
    $query = $entity_type_manager->getStorage('group')->getQuery();
    $query->condition('type', $group_type->id());
    $gids = $query->execute();

    // If we could not retrieve any group IDs, skip to the next group type.
    if (empty($gids)) {
      continue;
    }

    // Grab the anonymous or outsider role for the group type depending on the
    // user's account status (anonymous or authenticated).
    $group_role = $account->isAnonymous()
      ? $group_type->getAnonymousRole()
      : $group_type->getOutsiderRole();

    // Only check for permissions if the group type has the group_node plugin
    // installed for the node type.
    if (!$group_type->hasContentPlugin($plugin_id)) {
      continue;
    }

    if ($group_role->hasPermission("view {$plugin_id} entity")) {
      $grants += $gids;
    }
  }

  return [
    'gnode:section' => $grants,
  ];
}

/**
 * Implements hook_preprocess_html().
 */
function social_course_preprocess_html(&$variables) {
  $group = _social_group_get_current_group();

  if (!$group || !in_array($group->bundle(), ['course_basic', 'course_advanced'])) {
    return;
  }

  switch (\Drupal::routeMatch()->getRouteName()) {
    case 'entity.group.join':
      $variables['head_title']['title'] = t('Enroll in course @label', [
        '@label' => $group->label(),
      ]);
      break;

    case 'view.group_members.page_group_members':
      $variables['head_title']['title'] = t('Course members');
      break;

    case 'view.group_topics.page_group_topics':
      $variables['head_title']['title'] = t('Course Topics');
      break;

    case 'view.group_events.page_group_events':
      $variables['head_title']['title'] = t('Course Events');
      break;
  }
}

/**
 * Implements hook_preprocess_page_title().
 */
function social_course_preprocess_page_title(&$variables) {
  $group = _social_group_get_current_group();

  if (!$group || !in_array($group->bundle(), ['course_basic', 'course_advanced'])) {
    return;
  }

  switch (\Drupal::routeMatch()->getRouteName()) {
    case 'view.group_information.page_group_about':
      $variables['title'] = t('About course');
      break;

    case 'entity.group.join':
      $variables['title'] = t('Enroll in course %label', [
        '%label' => $group->label(),
      ]);
      break;

    case 'view.group_topics.page_group_topics':
      $variables['title'] = t('Course Topics');
      break;

    case 'view.group_events.page_group_events':
      $variables['title'] = t('Course Events');
      break;
  }
}

/**
 * Implements hook_preprocess_block().
 */
function social_course_preprocess_block(&$variables) {
  switch ($variables['elements']['#plugin_id']) {
    case 'views_block:upcoming_events-upcoming_events_group':
    case 'views_block:latest_topics-group_topics_block':
    case 'views_block:group_members-block_newest_members':
      $group = _social_group_get_current_group();

      if (!$group || !in_array($group->bundle(), ['course_basic', 'course_advanced'])) {
        return;
      }

      $variables['subtitle'] = t('in the course');
      break;

    case 'course_material_navigation':
      $nid = \Drupal::routeMatch()->getRawParameter('node');
      $storage = \Drupal::entityTypeManager()->getStorage('node');

      if (is_numeric($nid) && ($node = $storage->load($nid))) {
        /** @var \Drupal\social_course\CourseWrapperInterface $course_wrapper */
        $course_wrapper = \Drupal::service('social_course.course_wrapper');
        $course_wrapper->setCourseFromMaterial($node);

        if ($course_wrapper->getCourse()) {
          $section = $course_wrapper->getSectionFromMaterial($node);
          $variables['course_url'] = $course_wrapper->getCourse()->toUrl();
          $variables['section_number'] = $course_wrapper->getSectionNumber($section) + 1;
        }
      }
      break;
  }
}

/**
 * Implements hook_views_pre_render().
 */
function social_course_views_pre_render(ViewExecutable $view) {
  $key = $view->id() . ':' . $view->current_display;
  $group = _social_group_get_current_group();
  $course_wrapper = \Drupal::service('social_course.course_wrapper');
  $bundles = $course_wrapper::getAvailableBundles();

  if (!$group instanceof GroupInterface || !in_array($group->bundle(), $bundles)) {
    return;
  }

  switch ($key) {
    case 'upcoming_events:upcoming_events_group':
      $view->empty['area_text_custom']->options['content'] = t('No upcoming events in this course');
      break;

    case 'latest_topics:group_topics_block':
      $view->empty['area_text_custom']->options['content'] = t('No topics in this course');
      break;

    case 'group_members:block_newest_members':
      $view->empty['area_text_custom']->options['content'] = t('No members in this course');
      break;

    case 'group_members:page_group_members':
      $view->empty['area']->options['content']['value'] = t('No members in this course');
      break;

    case 'group_topics:page_group_topics':
      $view->empty['area_text_custom']->options['content'] = t('No topics in this course');
      break;

    case 'group_events:page_group_events':
      $view->empty['area_text_custom']->options['content'] = t('No events in this course');
      break;
  }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function social_course_theme_suggestions_group_alter(array &$suggestions, array $variables) {
  $group = $variables['elements']['#group'];

  if (in_array($group->bundle(), ['course_basic', 'course_advanced']) && $variables['elements']['#view_mode'] == 'hero') {
    $suggestions[] = 'group__course__hero';
  }
}

/**
 *  Implements hook_block_access().
 */
function social_course_block_access(Block $block, $operation, AccountInterface $account) {
  $material_types = [
    'article',
    'video',
  ];

  \Drupal::moduleHandler()->alter('social_course_material_types', $material_types);

  // Disable block for video and article node view pages.
  if ($operation == 'view' && $block->getPluginId() == 'social_page_title_block') {
    $nid = \Drupal::routeMatch()->getRawParameter('node');
    if (!empty($nid) && ($node = Node::load($nid))) {
      if (in_array($node->getType(), $material_types)) {
        return AccessResult::forbidden();
      }
    }
  }

  // Exclude Course navigation blocks form Add and Edit node pages.
  $course_blocks = [
    'course_material_navigation',
    'course_material_pager',
  ];
  if ($operation == 'view' && in_array($block->getPluginId(), $course_blocks)) {
    $route_name = \Drupal::routeMatch()->getRouteName();
    $excluded_routes = [
      'node.add',
      'entity.node.edit_form',
    ];
    if (in_array($route_name, $excluded_routes)) {
      return AccessResult::forbidden();
    }
  }

  // No opinion for other situations really.
  return AccessResult::neutral();
}

/**
 * Implements hook_preprocess_HOOK().
 */
function social_course_preprocess_node(&$variables) {
  $node = $variables['elements']['#node'];

  if ($node->bundle() == 'section') {
    // Load parent group (course).
    $group_content = GroupContent::loadByEntity($node);

    if (!$group_content) {
      return;
    }

    $group = current($group_content)->getGroup();
    $variables['parent_group'] = $group;
    $account = \Drupal::currentUser();
    /** @var \Drupal\social_course\CourseWrapperInterface $course_wrapper */
    $course_wrapper = \Drupal::service('social_course.course_wrapper');
    $course_wrapper->setCourse($group);

    $storage = \Drupal::entityTypeManager()->getStorage('course_enrollment');
    $entities = $storage->loadByProperties([
      'uid' => \Drupal::currentUser()->id(),
      'gid' => $group->id(),
      'sid' => $node->id(),
    ]);

    if (!$entities) {
      $variables['section_status'] = 'not-started';
      $variables['allowed_start'] = $course_wrapper->sectionAccess($node, \Drupal::currentUser(), 'start')->isAllowed();
    }
    else {
      foreach ($entities as $entity) {
        if ($entity->getStatus() === CourseEnrollmentInterface::IN_PROGRESS) {
          $variables['section_status'] = 'in-progress';
          $variables['section_current'] = $entity->get('mid')->target_id;
          break;
        }
        elseif ($entity->getStatus() === CourseEnrollmentInterface::FINISHED) {
          $variables['section_status'] = 'finished';
          $materials = $course_wrapper->getMaterials($node);
          $variables['section_current'] = current($materials)->id();
        }
      }
    }

    if (isset($variables['url']) && !$course_wrapper->sectionAccess($node, $account, 'view')->isAllowed()) {
      unset($variables['url']);
    }

    $variables['section_number'] = $course_wrapper->getSectionNumber($node) + 1;

    // Add node edit url for management.
    if ($variables['view_mode'] === 'teaser') {
      if ($node->access('update', $account)) {
        $variables['node_edit_url'] = $node->toUrl('edit-form')->toString();
      }
    }

  }
}

/**
 * Implements hook_node_access().
 */
function social_course_node_access(NodeInterface $node, $op, AccountInterface $account) {
  if ($op == 'view') {
    /** @var \Drupal\social_course\CourseWrapperInterface $course_wrapper */
    $course_wrapper = \Drupal::service('social_course.course_wrapper');

    if ($node->bundle() == 'section' && $course_wrapper->setCourseFromSection($node)->getCourse()) {
      return AccessResult::forbiddenIf(!$course_wrapper->sectionAccess($node, $account, 'view')->isAllowed());
    }
    elseif (($section = $course_wrapper->getSectionFromMaterial($node)) && $course_wrapper->setCourseFromSection($section)->getCourse()) {
      return AccessResult::forbiddenIf(!$course_wrapper->materialAccess($node, $account, 'view')->isAllowed());
    }
  }

  return AccessResult::neutral();
}

/**
 * Implements hook_entity_delete().
 */
function social_course_entity_delete(EntityInterface $entity) {
  switch ($entity->getEntityTypeId()) {
    case 'group':
      $storage = \Drupal::entityTypeManager()->getStorage('course_enrollment');
      $entities = $storage->loadByProperties([
        'gid' => $entity->id(),
      ]);

      foreach ($entities as $entity) {
        $entity->delete();
      }
      break;

    case 'node':
      $storage = \Drupal::entityTypeManager()->getStorage('course_enrollment');

      foreach (['sid', 'mid'] as $column) {
        $entities = $storage->loadByProperties([
          $column => $entity->id(),
        ]);

        foreach ($entities as $entity) {
          $entity->delete();
        }
      }
      break;

    case 'user':
      $storage = \Drupal::entityTypeManager()->getStorage('course_enrollment');

      $entities = $storage->loadByProperties([
        'uid' => $entity->id(),
      ]);

      foreach ($entities as $entity) {
        $entity->delete();
      }
      break;
  }
}

/**
 * Implements hook_entity_view().
 */
function social_course_entity_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if ($entity->id() && $entity->getEntityTypeId() == 'node' && $view_mode == 'full') {
    /** @var \Drupal\social_course\CourseWrapperInterface $course_wrapper */
    $course_wrapper = \Drupal::service('social_course.course_wrapper');
    $account = \Drupal::currentUser();

    if ($entity->bundle() == 'section') {
      $course_wrapper->setCourseFromSection($entity);
      $materials = $course_wrapper->getMaterials($entity);
      $material = current($materials);

      if ($course_wrapper->getCourse() && !$course_wrapper->courseIsSequential() && $material) {
        // Join user to course.
        $storage = \Drupal::entityTypeManager()->getStorage('course_enrollment');
        $entities = $storage->loadByProperties([
          'gid' => $course_wrapper->getCourse()->id(),
          'sid' => $entity->id(),
          'mid' => $material->id(),
          'uid' => $account->id(),
        ]);

        if (!$entities) {
          $storage->create([
            'gid' => $course_wrapper->getCourse()->id(),
            'sid' => $entity->id(),
            'mid' => $material->id(),
            'status' => CourseEnrollmentInterface::IN_PROGRESS,
          ])->save();
        }
      }
    }
    elseif ($section = $course_wrapper->getSectionFromMaterial($entity)) {
      $course_wrapper->setCourseFromSection($section);

      if ($course_wrapper->getCourse() && !$course_wrapper->courseIsSequential()) {
        // Join user to course.
        $storage = \Drupal::entityTypeManager()->getStorage('course_enrollment');
        $entities = $storage->loadByProperties([
          'gid' => $course_wrapper->getCourse()->id(),
          'sid' => $section->id(),
          'mid' => $entity->id(),
          'uid' => $account->id(),
        ]);

        if (!$entities) {
          $storage->create([
            'gid' => $course_wrapper->getCourse()->id(),
            'sid' => $section->id(),
            'mid' => $entity->id(),
            'status' => CourseEnrollmentInterface::IN_PROGRESS,
          ])->save();
        }
      }
    }
  }
}

/**
 * Implements hook_entity_base_field_info().
 */
function social_course_entity_base_field_info(EntityTypeInterface $entity_type) {
  if ($entity_type->id() == 'group') {
    $fields['status'] = BaseFieldDefinition::create('boolean')
      ->setLabel(t('Published'))
      ->setRevisionable(TRUE)
      ->setTranslatable(TRUE)
      ->setDefaultValue(TRUE)
      ->setDisplayOptions('view', [
        'label' => 'hidden',
        'type' => 'hidden',
        'weight' => -5,
      ])
      ->setDisplayOptions('form', [
        'weight' => -5,
      ])
      ->setDisplayConfigurable('form', TRUE);

    return $fields;
  }
}

/**
 * Implements hook_query_alter().
 */
function social_course_query_alter(AlterableInterface $query) {
  if (!$query instanceof SelectInterface) {
    return;
  }

  $tables = $query->getTables();

  if (!isset($tables['groups_field_data'])) {
    return;
  }

  if (!$account = $query->getMetaData('account')) {
    $account = \Drupal::currentUser();
  }
  else {
    $account = \Drupal::currentUser();
  }

  if ($account->hasPermission('bypass group access')) {
    return;
  }

  if (!$account->hasPermission('view unpublished groups')) {
    $alias = $tables['groups_field_data']['alias'];
    $or = $query->orConditionGroup();
    $or->condition("{$alias}.status", 1);

    // If user has access to view own unpublished groups.
    if ($account->hasPermission('view own unpublished groups')) {
      $or->condition("{$alias}.uid", $account->id());
    }

    $query->condition($or);
  }
}

/**
 * Implements hook_field_widget_form_alter().
 */
function social_course_field_widget_form_alter(&$element, FormStateInterface $form_state, $context) {
  $form_object = $form_state->getFormObject();

  if (!$form_object instanceof EntityFormInterface) {
    return;
  }

  $entity = $form_object->getEntity();

  if ($entity->getEntityTypeId() == 'group' && $context['items']->getName() == 'status') {
    /** @var \Drupal\social_course\CourseWrapperInterface $course_wrapper */
    $course_wrapper = \Drupal::service('social_course.course_wrapper');

    if (!in_array($entity->bundle(), $course_wrapper::getAvailableBundles())) {
      $element['#access'] = FALSE;
      return;
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function social_course_group_presave(GroupInterface $entity) {
  if ($entity->hasField('field_course_opening_date') && $entity->hasField('field_course_opening_status')) {
    if ($date = $entity->get('field_course_opening_date')->value) {
      $status = $date <= gmdate("Y-m-d\TH:i:00");
      $entity->get('field_course_opening_status')->value = $status;
    }
  }
}

/**
 * Implements hook_cron().
 */
function social_course_cron() {
  /** @var \Drupal\social_course\CourseWrapperInterface $course_wrapper */
  $course_wrapper = \Drupal::service('social_course.course_wrapper');
  $query = \Drupal::entityQuery('group')
    ->condition('type', $course_wrapper::getAvailableBundles(), 'IN')
    ->condition('field_course_opening_status', FALSE)
    ->condition('field_course_opening_date', gmdate("Y-m-d\TH:i:00"), '<=')
    ->range(0, 20);

  if ($results = $query->execute()) {
    $storage = \Drupal::entityTypeManager()->getStorage('group');

    if ($entities = $storage->loadMultiple($results)) {
      foreach ($entities as $entity) {
        if (!$entity->get('field_course_opening_status')->value) {
          // todo: send notifications.
        }

        $entity->save();
      }
    }
  }
}
